name: newsboat
version: git
summary: An RSS/Atom feed reader for text terminals
description: |
  Newsboat is an RSS/Atom feed reader for the text console. It's an actively
  maintained fork of Newsbeuter.
grade: stable
confinement: strict

apps:
  newsboat:
    command: usr/local/bin/newsboat
    environment:
      LOCPATH: "$SNAP/usr/lib/locale"
    plugs:
      - network
      - home
      - desktop
  podboat:
    command: usr/local/bin/podboat
    environment:
      LOCPATH: "$SNAP/usr/lib/locale"
    plugs:
      - network
      - home
      - desktop

parts:
  newsboat:
    plugin: make
    source: .
    build-packages: 
      - pkg-config
      - libsqlite3-dev
      - libcurl4-openssl-dev
      - libxml2-dev
      - libstfl-dev
      - libjson-c-dev
      - libncursesw5-dev
      - asciidoctor
      - libssl-dev
      - gettext
      - cargo
    stage-packages:
      - libxml2
      - librtmp1
      - locales-all
      - libcurl3
      - libstfl0
